[project]
name = "zimagelatent"
description = "A super simple node that outputs official zimage resolutions as a latent"
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/HellerCommaA/ComfyUI-ZImageLatent"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "hellercommaa"
DisplayName = "ComfyUI-ZImageLatent"
Icon = ""
